# Generated by Django 4.0.2 on 2022-06-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('about', models.TextField(max_length=500)),
                ('content', models.TextField(max_length=1024)),
                ('author', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='news/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
