# Generated by Django 4.0.2 on 2022-06-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_delete_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
    ]
